# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-30 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20180327_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantlocation',
            old_name='update',
            new_name='updated',
        ),
    ]
