# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-02 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20180330_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='updated',
        ),
    ]
